server:
  port: 8080
  servlet:
    context-path: /FoodDeliveryApp
kafka:
  bootstrapServerAddress: localhost:9092
  order:
    topicName: Order
spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages:*